### ISSUE TITLE
RFE: Making generated example more complete

### ISSUE THREAD

**Issue by tjyang** [mholt/curl-to-go#1]
Hi Thanks for this great software.

Would you please enhance the generated go code to be almost ready-to-run ?

Goal is to have user modify variable part(actual site url and login account/password).

**Comment by mholt** [comment]
So like

``` go
package main

func main() {
   // insert generated code here
   // then add imports above
   // and some sort of output here, probably
}
```

?

The point of this tool is to produce code you can drop in to an existing Go project. But making it a full Go program is just a few extra, trivial lines.

**Comment by tjyang** [comment]
Yes, exactly. make the example 1-5 run-able as many as possible after generation. So beginner(like me) can just copy and paste the example code to have a test run.

**Comment by mholt** [comment]
I think that's a little outside the scope of this project, but other beginners with your question can find this issue and use my post above as an example. (Besides, the examples are contrived, only to show off what the tool can do.) Also, I recommend the Go tour for all newbies: https://tour.golang.org

Thanks for your feedback!
