### ISSUE TITLE
Go's default http client follows redirection while curl does not

### ISSUE THREAD

**Issue by orcaman** [mholt/curl-to-go#14]
Hi,

The use of the default http client (`resp, err := http.DefaultClient.Do(req)` causes a bug: when the response returns a redirection, go's default http client follows that redirection by default, while curl does not. 

The client in use here should be changed from the default client to this:

```go
client := &http.Client{
    CheckRedirect: func(req *http.Request, via []*http.Request) error {
        return http.ErrUseLastResponse
    },
}
```

This will fix this incolcnsistany with curl. 

Cheers

**Comment by mholt** [comment]
I'm glad you pointed out this inconsistency... I need to decide if we want to make http.Client values automatically here or just stick with http.DefaultClient, since clients are supposed to be reused...

**Comment by EugenMayer** [comment]
this needs then alignment with the `--location` command which is very important with curl usage, so then, following a redirect should be done

**Comment by mholt** [comment]
Documented with b9a94c33e7f2bacd138eb3d4e68b455dcdf65fbc
