### ISSUE TITLE
Host Headers

### ISSUE THREAD

**Issue by xfreakart** [mholt/curl-to-go#15]
After some minutes of fight, I saw that if in a curl like:
(Purge for Varnish stuff)
 curl -v -X PURGE -H "Host: www.xxxx.com" .... 

from: *request.go
        // For server requests Host specifies the host on which the
	// URL is sought. Per RFC 2616, this is either the value of
	// the "Host" header or the host name given in the URL itself.
	// It may be of the form "host:port". For international domain
	// names, Host may be in Punycode or Unicode form. Use
	// golang.org/x/net/idna to convert it to either format if
	// needed.
	//
	// For client requests Host optionally overrides the Host
	// header to send. If empty, the Request.Write method uses
	// the value of URL.Host. Host may contain an international
	// domain name.

Bad -> req.Header.Set("Host", "www.xxxx.com")
Good -> req.Host = "www.xxxx.com" 

At least in:  go version go1.8.1 linux/amd64

**Comment by mholt** [comment]
Ah, so we need to add a special case for the Host header to set it differently. Noted, thanks!

PR welcome. ;) Been a bit busy with a conference paper deadline this week.
