### ISSUE TITLE
Send file to file.io

### ISSUE THREAD

**Issue by MikhailKlemin** [mholt/curl-to-go#17]
Hi the file.io has curl like this 
curl -F "file=@test.txt" https://file.io

It doesn't seems like converts correctly by curl-to-go....

**Comment by mholt** [comment]
You closed this; did it get fixed? 🤔

**Comment by MikhailKlemin** [comment]
No... But I decided not to use file.io anyway. And since there was no reply since 28 June, closed it to reduce burden on developers :-)

**Comment by mholt** [comment]
Well, we can still consider it. The intro paragraph _does_ mention the flags that are supported, and -F isn't one of them. So this is a feature request.

This is the output right now:

```
// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
resp, err := http.Get("https://file.io")
if err != nil {
	// handle err
}
defer resp.Body.Close()
```

**Comment by mholt** [comment]
Due to constraints on my time, I'll be happy to implement this, but someone should please provide the equivalent Go code and I'll try to work it in. Can re-open at that time. Thanks!
