### ISSUE TITLE
--data-binary should do POST not GET

### ISSUE THREAD

**Issue by edbond** [mholt/curl-to-go#20]
--data-binary <data>

(HTTP) This posts data exactly as specified with no extra processing whatsoever.

If you start the data with the letter @, the rest should be a filename. Data is posted in a similar manner as -d, --data does, except that newlines and carriage returns are preserved and conversions are never done.

If this option is used several times, the ones following the first will append data as described in -d, --data.

**Comment by mholt** [comment]
Fixed in #25
