### ISSUE TITLE
--form POST

### ISSUE THREAD

**Issue by avelino** [mholt/curl-to-go#22]

**Comment by mholt** [comment]
I don't know what this means :-/

**Comment by avelino** [comment]
` -F, --form CONTENT  Specify HTTP multipart POST data (H)`
example:
```
curl  --form "field=value" https://...
```

**Comment by mholt** [comment]
Oh. Are you requesting this feature to be added?

**Comment by avelino** [comment]
Yeah

**Comment by mholt** [comment]
Okay. More than two words would have been nice. :)

**Comment by mholt** [comment]
Due to constraints on my time, I'll be happy to add this feature but can only work on it if the requester (or somebody) can provide the equivalent Go code for a curl command. I simply don't have the time to figure that out right now. Will re-open if the Go code and a curl command is provided.

**Comment by 89z** [comment]
https://github.com/mholt/curl-to-go/issues/22
https://github.com/mholt/curl-to-go/issues/28
https://github.com/mholt/curl-to-go/issues/34
