### ISSUE TITLE
curl -d should generate POST requests

### ISSUE THREAD

**Issue by campoy** [mholt/curl-to-go#3]
Given

``` bash
curl -d "" google.com 
```

the program generates:

``` go
body := strings.NewReader(`google.com`)
req, err := http.NewRequest("GET", "", body)
if err != nil {
    // handle err
}

client := http.Client{}
resp, err := client.Do(req)
if err != nil {
    // handle err
}
defer resp.Body.Close()
```

but `curl` will perform a POST request, not GET

**Comment by campoy** [comment]
Also, notice that google.com is being used as data, instead of using the given empty string `""`.

**Comment by mholt** [comment]
Oops, you're right on both counts. Pushing a fix soon. Thanks for the report!
