### ISSUE TITLE
The code is wrong

### ISSUE THREAD

**Issue by ppabc** [mholt/curl-to-go#32]
**Are you requesting support for a new curl flag? If so, what is the flag and the equivalent Go code?**
The code is wrong
```bash
#curl --resolve www.aqzt.com:80:127.0.0.1 http://www.aqzt.com
```

```go

// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
resp, err := http.Get("http://www.aqzt.com")
if err != nil {
	// handle err
}
defer resp.Body.Close()
```

**Comment by mholt** [comment]
This is not particularly helpful. Can you provide more details? Closing otherwise.
