### ISSUE TITLE
Use `http.MethodX` constants instead of strings

### ISSUE THREAD

**Issue by Ullaakut** [mholt/curl-to-go#56]
Given the following curl command,

```bash
curl -X POST google.com -d '{}'
```

The result should use `http.MethodPost`

```go
req, err := http.NewRequest(http.MethodPost, "google.com", body)
```

But instead it currently uses a `"POST"` string, which is not ideal.

**Comment by mholt** [comment]
I agree. I think those constants didn't exist when I wrote this (or I just didn't know about them). Good easy improvement if you want to submit a Pr!
