### ISSUE TITLE
Header by default not implemented

### ISSUE THREAD

**Issue by kindermoumoute** [mholt/curl-to-go#8]
I'm currently using [etcd](https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html) which brings me to use your awesome  curl-to-go converter. However when trying a basic command like putting a value:
`curl -L -X PUT http://127.0.0.1:2379/v2/keys/message -d value="Hello"`

This generate this:

```
// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

body := strings.NewReader(`value=Hello`)
req, err := http.NewRequest("PUT", "http://127.0.0.1:2379/v2/keys/message", body)
if err != nil {
    // handle err
}

resp, err := http.DefaultClient.Do(req)
if err != nil {
    // handle err
}
defer resp.Body.Close()
```

The Curl command works but this code doesn't. The reason is one of the Curl default header is not set:
`req.Header.Set("Content-Type", "application/x-www-form-urlencoded")`

This should be the generated code that actually works with my code:

```
// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

body := strings.NewReader(`value=Hello`)
req, err := http.NewRequest("PUT", "http://127.0.0.1:2379/v2/keys/message", body)
if err != nil {
    // handle err
}
req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

resp, err := http.DefaultClient.Do(req)
if err != nil {
    // handle err
}
defer resp.Body.Close()
```

**Comment by mholt** [comment]
Ah, so curl adds that header when using `-d`, is that correct?

**Comment by kindermoumoute** [comment]
It seems yeah. Also I'm not sure if this is the only header it adds.
